<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <AssemblyName>Restless.App.Toolkit</AssemblyName>
    <Authors>Restless Animal Development</Authors>
    <Company>Restless Animal Development</Company>
    <Description>Sample app to demonstrate various controls of Restless Toolkit</Description>
    <OutputType>WinExe</OutputType>
    <PackageId>Restless.App.Toolkit</PackageId>
    <Product>Restless.Toolkit.App</Product>
    <RootNamespace>Restless.App.Toolkit</RootNamespace>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Version>1.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Restless.Toolkit\Restless.Toolkit.csproj" />
  </ItemGroup>

</Project>