<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Restless.Toolkit</AssemblyName>
    <Authors>Restless Animal Development</Authors>
    <Company>Restless Animal Development</Company>
    <Copyright>Copyright © 2022 Restless Animal Development</Copyright>
    <Description>Provides simple mvm base classes and various custom controls for use in WPF applications.</Description>
    <LangVersion>10</LangVersion>
    <OutputType>Library</OutputType>
    <PackageId>Restless.Toolkit</PackageId>
    <PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/victor-david/restless-toolkit</PackageProjectUrl>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageTags>wpf controls wpf-controls mvvm</PackageTags>
    <Product>Restless Toolkit</Product>
    <RepositoryUrl>https://github.com/victor-david/restless-toolkit</RepositoryUrl>
    <RootNamespace>Restless.Toolkit</RootNamespace>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Title>Restless.Toolkit</Title>
    <UseWpf>true</UseWpf>
    <Version>2.5.25</Version>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>Restless.Toolkit.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WpfScreenHelper" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="InternalResources\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="InternalResources\Strings.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>